version: "3.7"

services:
  db:
    network_mode: "host"
    container_name: fitness-tracker-db
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env.local #Here we are using the already existing .env.local file
    ports:
      - "5432:5432"

  db-test:
    network_mode: "host"
    container_name: fitness-tracker-db-test
    image: postgres:latest
    env_file: ./.env.test.local
    ports:
      - "5433:5433"

volumes:
  data:
